version: '3.8'

services:
  web:
    build: ./fe
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    networks:
      - crypto-network

  backend-service:
    build: ./be
    ports:
      - "5003:5001"
    depends_on:
      - mysqldb
    networks:
      - crypto-network

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
